name: 'Azure Manage Layer Workflow'

on:
  push:
    branches:
    - main
    paths:
    - 'layers/manage/**'
    - '.github/workflows/azure-manage-layer.yaml'
    - 'environments/layer/manage/**'
  pull_request:
    branches:
    - main    
    paths:
    - 'layers/manage/**'
    - '.github/workflows/azure-manage-layer.yaml'
    - 'environments/layer/manage/**'

jobs:
  deploy-npd:
    if: github.event_name == 'pull_request' || github.ref_name == 'main'
    uses: AnoopHegde/platformengine-reusable-workflows/.github/workflows/terraform-deploy-azure-simple.yaml@main
    with:
      github-env: npd
      environment: npd
      working-directory: layers/manage/virtual-machines
      vars-path: ../../../environments/layer/manage/npd/virtual-machines/env.tfvars
      backend-path: ../../../environments/layer/manage/npd/virtual-machines/backend.tfvars
      runner-label: pe-arc-runner-shared-npd
    secrets: inherit    